service:
  name: auth

plugins:
  - serverless-offline
  - serverless-jetpack
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  stage: dev
  profile: wet
  versionFunctions: false

custom:
  project: kaishahero
  service_name: auth
  stage: ${opt:stage, self:provider.stage}
  jetpack:
    base: '../../'

package:
  individually: true
  include:
    - 'node_modules/**'
    - '!{../,}{**/,}node_modules/aws-sdk/**'
    - '!{../,}{**/,}node_modules/{@*/*,*}/CHANGELOG.md'
    - '!{../,}{**/,}node_modules/{@*/*,*}/README.md'

functions:
  graphql:
    handler: handler.handleGraphql
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy
